name: CI
on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
      - run: npm install
      - run: npm run build --if-present
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
      - run: npm install
      - run: npm run lint --if-present
  Test:
    strategy:
      matrix:
        node-version: [ 10, 12, 14, 15 ]
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test --if-present
      - run: npm run coverage --if-present
